//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinica
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FisioterapiayOsteopatiaArielMongeEntities : DbContext
    {
        public FisioterapiayOsteopatiaArielMongeEntities()
            : base("name=FisioterapiayOsteopatiaArielMongeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Citas> Citas { get; set; }
        public virtual DbSet<EstadosTratamiento> EstadosTratamiento { get; set; }
        public virtual DbSet<Facturacion> Facturacion { get; set; }
        public virtual DbSet<HistorialMedico> HistorialMedico { get; set; }
        public virtual DbSet<HistorialPacientes> HistorialPacientes { get; set; }
        public virtual DbSet<Horarios> Horarios { get; set; }
        public virtual DbSet<Inventario> Inventario { get; set; }
        public virtual DbSet<Pacientes> Pacientes { get; set; }
        public virtual DbSet<Profesionales> Profesionales { get; set; }
        public virtual DbSet<Salas> Salas { get; set; }
        public virtual DbSet<Servicios> Servicios { get; set; }
        public virtual DbSet<ServiciosPrestados> ServiciosPrestados { get; set; }
        public virtual DbSet<Tratamientos> Tratamientos { get; set; }
    }
}
