//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinica
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiciosPrestados
    {
        public int ServicioPrestadoID { get; set; }
        public int CitaID { get; set; }
        public int ServicioID { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Monto { get; set; }
    
        public virtual Citas Citas { get; set; }
        public virtual Servicios Servicios { get; set; }
    }
}
