//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinica
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tratamientos
    {
        public int TratamientoID { get; set; }
        public int PacienteID { get; set; }
        public string TipoTratamiento { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public int EstadoID { get; set; }
    
        public virtual EstadosTratamiento EstadosTratamiento { get; set; }
        public virtual Pacientes Pacientes { get; set; }
    }
}
